/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as RssRouteImport } from './routes/rss'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as PostsSplatRouteImport } from './routes/posts.$'
import { Route as NotesSplatRouteImport } from './routes/notes.$'
import { Route as ApiFollowerRouteImport } from './routes/api/follower'
import { Route as ApiAudioTracksRouteImport } from './routes/api/audio-tracks'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSplatRoute = PostsSplatRouteImport.update({
  id: '/posts/$',
  path: '/posts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSplatRoute = NotesSplatRouteImport.update({
  id: '/notes/$',
  path: '/notes/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowerRoute = ApiFollowerRouteImport.update({
  id: '/api/follower',
  path: '/api/follower',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioTracksRoute = ApiAudioTracksRouteImport.update({
  id: '/api/audio-tracks',
  path: '/api/audio-tracks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/rss': typeof RssRoute
  '/sitemap': typeof SitemapRoute
  '/api/audio-tracks': typeof ApiAudioTracksRoute
  '/api/follower': typeof ApiFollowerRoute
  '/notes/$': typeof NotesSplatRoute
  '/posts/$': typeof PostsSplatRoute
  '/notes': typeof NotesIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/rss': typeof RssRoute
  '/sitemap': typeof SitemapRoute
  '/api/audio-tracks': typeof ApiAudioTracksRoute
  '/api/follower': typeof ApiFollowerRoute
  '/notes/$': typeof NotesSplatRoute
  '/posts/$': typeof PostsSplatRoute
  '/notes': typeof NotesIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/rss': typeof RssRoute
  '/sitemap': typeof SitemapRoute
  '/api/audio-tracks': typeof ApiAudioTracksRoute
  '/api/follower': typeof ApiFollowerRoute
  '/notes/$': typeof NotesSplatRoute
  '/posts/$': typeof PostsSplatRoute
  '/notes/': typeof NotesIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/impressum'
    | '/rss'
    | '/sitemap'
    | '/api/audio-tracks'
    | '/api/follower'
    | '/notes/$'
    | '/posts/$'
    | '/notes'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/impressum'
    | '/rss'
    | '/sitemap'
    | '/api/audio-tracks'
    | '/api/follower'
    | '/notes/$'
    | '/posts/$'
    | '/notes'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/impressum'
    | '/rss'
    | '/sitemap'
    | '/api/audio-tracks'
    | '/api/follower'
    | '/notes/$'
    | '/posts/$'
    | '/notes/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImpressumRoute: typeof ImpressumRoute
  RssRoute: typeof RssRoute
  SitemapRoute: typeof SitemapRoute
  ApiAudioTracksRoute: typeof ApiAudioTracksRoute
  ApiFollowerRoute: typeof ApiFollowerRoute
  NotesSplatRoute: typeof NotesSplatRoute
  PostsSplatRoute: typeof PostsSplatRoute
  NotesIndexRoute: typeof NotesIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$': {
      id: '/posts/$'
      path: '/posts/$'
      fullPath: '/posts/$'
      preLoaderRoute: typeof PostsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$': {
      id: '/notes/$'
      path: '/notes/$'
      fullPath: '/notes/$'
      preLoaderRoute: typeof NotesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/follower': {
      id: '/api/follower'
      path: '/api/follower'
      fullPath: '/api/follower'
      preLoaderRoute: typeof ApiFollowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio-tracks': {
      id: '/api/audio-tracks'
      path: '/api/audio-tracks'
      fullPath: '/api/audio-tracks'
      preLoaderRoute: typeof ApiAudioTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImpressumRoute: ImpressumRoute,
  RssRoute: RssRoute,
  SitemapRoute: SitemapRoute,
  ApiAudioTracksRoute: ApiAudioTracksRoute,
  ApiFollowerRoute: ApiFollowerRoute,
  NotesSplatRoute: NotesSplatRoute,
  PostsSplatRoute: PostsSplatRoute,
  NotesIndexRoute: NotesIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
