import Image from "next/image";
import React from "react";
import { FC, Suspense } from "react";
import Subpart from "./subpart.client";

const MastHead: FC<{
  count: {
    total: number;
    youtube: number;
    github: number;
    devto: number;
    mastodon: number;
  };
}> = ({ count }) => {
  return (
    <section className="relative">
      {/* Illustration behind hero content */}

      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        {/* Hero content */}
        <div className="pt-32 pb-12 md:pt-40 md:pb-20">
          {/* Section header */}
          <div className="text-center pb-12 md:pb-16">
            <h1
              className="text-5xl md:text-6xl font-extrabold leading-tighter tracking-tighter mb-4"
              data-aos="zoom-y-out"
            >
              Welcome to the old{" "}
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-teal-400">
                WebDev{" "}
              </span>
            </h1>
          </div>
          <Subpart count={count} />
          {/* Hero image */}
          <Image
            src="/ava2023.png"
            width="500"
            height="500"
            alt="Avatar of Andi generated by Midjourney AI"
          />
        </div>
      </div>
    </section>
  );
};

export default MastHead;
